trigger:
  branches:
    include:
    - master
    - refs/tags/v*.*.*-*

jobs:
- job:
  displayName: 'Snapshot build'
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  pool:
    vmImage: 'ubuntu-latest'

  container: nicholasterry/azure-pipelines-alpine:latest

  steps:
  - checkout: self
    submodules: true

  - script: sudo apk add build-base openjdk11 maven
    displayName: 'Setup prerequisite(s)'

  - script: |
      mvn versions:set -DnewVersion=$(Build.BuildNumber)
      mvn clean install

    displayName: 'Build artifact(s)'

- job:
  displayName: 'Release build'
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  pool:
    vmImage: 'ubuntu-latest'

  container: nicholasterry/azure-pipelines-alpine:latest

  steps:
    - checkout: self
      submodules: true

    - script: sudo apk add build-base openjdk11 maven
      displayName: 'Setup prerequisite(s)'

    - script: |
        versionTag=$(echo '$(Build.SourceBranchName)' | tr -d 'v')
        mvn versions:set -DnewVersion=${versionTag}
        mvn clean install

      displayName: 'Build artifact(s)'
